export HYPOLAS_HEALCHECK_HTTP_EXPECTED=down
export HYPOLAS_HEALCHECK_HTTP_HEADERS=firstHeader,firstValue__Authorization,"Basic dGVzdDp0ZXN0MTIz"
export HYPOLAS_HEALCHECK_HTTP_JSON=headers__Accept-Encoding
export HYPOLAS_HEALCHECK_HTTP_PROXY=
export HYPOLAS_HEALCHECK_HTTP_URL=https://httpbin.org/get
export HYPOLAS_HEALCHECK_TYPE=http